### ISSUE TITLE
update to 1.0.5.1

### ISSUE THREAD

**Issue by Denzel76** [cupidare/OsCommerce-CE-Phoenix-German-language-Deutsches-Sprachpaket#14]
german.php ist fertig, aber ich habe gelernt nicht zum master zu pullen, also musst du erstmal einen 1.0.5.1 Branch erzeugen... ;)

**Comment by cupidare** [comment]
Guten Morgen, ich war leider länger auf Dienstreise... da die Entwicklung sehr schnell voranschreitet, hab ich mal ein paar Änderungen angefangen... ich versuche die mal die nächsten Tage hochzuladen

**Comment by cupidare** [comment]
Ich  habe mal alles nach 1.0.5.4 übersetzt. Allerdings war es recht viel... Tests wären super
